yml file should be good to go. file should commit

diff --git a/.github/workflows/onPull.yml b/.github/workflows/onPull.yml
--- a/.github/workflows/onPull.yml
+++ b/.github/workflows/onPull.yml
@@ -1,57 +1,57 @@
-# name: kuberform
+name: kuberform
 
-# on: [pull_request]
+on: [pull_request]
 
-# jobs:
-#   buildKuberform:
-#     runs-on: ubuntu-latest
-#     strategy:
-#       matrix:
-#         node-version: ['18.12.0']
+jobs:
+  buildKuberform:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version: ['18.12.0']
 
-#     steps:
+    steps:
 
-#     - name: See if patch label exists
-#       if: contains(github.event.pull_request.labels.*.name,'patch')
-#       run: echo "VersionType=patch" >> $GITHUB_ENV
+    - name: See if patch label exists
+      if: contains(github.event.pull_request.labels.*.name,'patch')
+      run: echo "VersionType=patch" >> $GITHUB_ENV
 
-#     - name: See if minor label exists
-#       if: contains(github.event.pull_request.labels.*.name,'minor')
-#       run: echo "VersionType=minor" >> $GITHUB_ENV
+    - name: See if minor label exists
+      if: contains(github.event.pull_request.labels.*.name,'minor')
+      run: echo "VersionType=minor" >> $GITHUB_ENV
 
-#     - name: See if major label exists
-#       if: contains(github.event.pull_request.labels.*.name,'major')
-#       run: echo "VersionType=major" >> $GITHUB_ENV
+    - name: See if major label exists
+      if: contains(github.event.pull_request.labels.*.name,'major')
+      run: echo "VersionType=major" >> $GITHUB_ENV
 
-#     - name: Throw error if VersionType is empty
-#       if: "${{ env.VersionType == '' }}"
-#       run: echo "Error!"; exit 125
+    - name: Throw error if VersionType is empty
+      if: "${{ env.VersionType == '' }}"
+      run: echo "Error!"; exit 125
 
-#     - uses: actions/checkout@v3
-#       with:
-#         fetch-depth: 2
-#     - run: git checkout HEAD^
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 2
+    - run: git checkout HEAD^
 
-#     - name: install app-src modules
-#       working-directory: /home/runner/work/kuberform/kuberform/app-src
-#       run: npm install
+    - name: install app-src modules
+      working-directory: /home/runner/work/kuberform/kuberform/app-src
+      run: npm install
 
-#     - name: install root modules
-#       working-directory: /home/runner/work/kuberform/kuberform
-#       run: npm install
+    - name: install root modules
+      working-directory: /home/runner/work/kuberform/kuberform
+      run: npm install
 
-#     - name: test the code
-#       working-directory: /home/runner/work/kuberform/kuberform/app-src
-#       run: npm test
+    - name: test the code
+      working-directory: /home/runner/work/kuberform/kuberform/app-src
+      run: npm test
 
-#     - name: check Linting
-#       working-directory: /home/runner/work/kuberform/kuberform/app-src
-#       run: npm run linter
+    - name: check Linting
+      working-directory: /home/runner/work/kuberform/kuberform/app-src
+      run: npm run linter
 
-#     - name: build
-#       working-directory: /home/runner/work/kuberform/kuberform/app-src
-#       run: npm run build
+    - name: build
+      working-directory: /home/runner/work/kuberform/kuberform/app-src
+      run: npm run build
 
-#     - name: rollup kuberform
-#       working-directory: /home/runner/work/kuberform/kuberform
-#       run: npm run rollup
+    - name: rollup kuberform
+      working-directory: /home/runner/work/kuberform/kuberform
+      run: npm run rollup
