update to yml file for auto deploy

diff --git a/.github/workflows/onPull.yml b/.github/workflows/onPull.yml
--- a/.github/workflows/onPull.yml
+++ b/.github/workflows/onPull.yml
@@ -10,9 +10,6 @@ jobs:
         node-version: ['18.12.0']
 
     steps:
-    - name: Dump GitHub context
-      id: github_context_step
-      run: echo '${{ toJSON(github.event.pull_request.labels) }}'
 
     - name: see if patch label exists
       if: contains(github.event.pull_request.labels.*.name,'patch')
@@ -27,10 +24,22 @@ jobs:
       run: echo "VersionType=major" >> $GITHUB_ENV
 
     - name: check to see if env is set
-      run: echo "${{env.VersionType}}"
+      run: echo "${{env.VersionType}}"; if [ condition ]; then
 
-    - name: git checkout
+    - name: throw error if VersionType is empty
+      if: "${{ env.VersionType == '' }}"
+      run: echo "Error!"; exit 125
+
+    - name: Checkout
       uses: actions/checkout@v3
+    - run: |
+          nvm ${{ env.VersionType}}
+          git config user.name GitHub Actions Bot
+          git config user.email github-actions@github.com
+          git add .
+          git commit -m "version controll ${{ env.VersionType}}"
+          git push
+
 
     #   if pr is merged get the label from the merged pr and find a way to update the main branch
 
